### ISSUE TITLE
Menú del programa

### ISSUE THREAD

**Issue by orgynmobs** [aigora/twIE_2021-mercado_etsidi#5]
Debéis generar código que implemente un **menú provisional** con el que el usuario de vuestro programa debe interactuar. Este menú debe contener las opciones necesarias para acceder a las funcionalidades previstas, aunque aún no realizará ninguna acción. 
El menú estará implementado mediante un bucle `switch-case` y se repetirá indefinidamente hasta que el usuario decida salir del programa.

**Comment by oscarperpinan** [comment]
El código del menú debe estar contenido en un fichero con extensión .c

**Comment by lquintanac** [comment]
Buenas, recordad cerrar la issue una vez subido el archivo del menú. También una vez cerrada esta issue debéis cerrar la milestone Versión alfa.
