### ISSUE TITLE
Diagrama de flujo

### ISSUE THREAD

**Issue by orgynmobs** [aigora/twIE_2021-mercado_etsidi#6]
Debéis crear un fichero en formato [PDF](https://help.github.com/en/articles/rendering-pdf-documents), [GIF, JPEG o PNG](https://help.github.com/en/articles/rendering-and-diffing-images) (**no se admiten documentos Word o similar**) representando el [diagrama de flujo](https://es.wikipedia.org/wiki/Diagrama_de_flujo) previsto para vuestro programa. 
En el punto de inicio tenéis un [tutorial](https://github.com/aigora/punto_inicio/wiki/6.1-C%C3%B3mo-realizar-un-diagrama-de-flujo) para crear diagramas de flujo.
Este diagrama os servirá de guía para la implementación del trabajo. No obstante, ésta será la primera versión, por lo que según vayáis avanzando en el desarrollo del programa podréis y deberéis modificarlo.

**Comment by hectorgutierrezv** [comment]
![DIAGRAMA-FLUJO](https://user-images.githubusercontent.com/79969704/114012027-23d24100-9866-11eb-864b-e5d2b3c053d3.png)

**Comment by InesMelendez** [comment]
La simbología del diagrama de flujo no es del todo correcta.

**Comment by InesMelendez** [comment]
[Diagrama de flujo.pdf](https://github.com/aigora/twIE_2021-mercado_etsidi/files/6278777/Diagrama.de.flujo.pdf)

**Comment by oscarperpinan** [comment]
El diagrama debe estar en un fichero contenido dentro del repositorio, como un fichero más.

**Comment by orgynmobs** [comment]
Habéis subido los ficheros pero os falta cerrar la issue. Podéis hacerlo justo aquí abajo
